### ISSUE TITLE
WeightedBigraph#maximum_weighted_matching hangs forever

### ISSUE THREAD

**Issue by bblimke** [jaredbeck/graph_matching#10]
`maximum_weighted_matching` hangs forever in the following example:

````
g = GraphMatching::Graph::WeightedBigraph[[1, 2, 1], [3, 2, 1], [3, 4, 1], [3, 5, 1], [6, 2, 1], [6, 4, 1], [6, 5, 1]]
m = g.maximum_weighted_matching
````

**Comment by jaredbeck** [comment]
Hi Bartosz, it's been years since I've worked on this gem, but let's see what we can figure out. First, I'm pretty sure your graph *is* bipartite, so that's good :grin:

![issue_10_coloring](https://user-images.githubusercontent.com/380809/74095764-42eb0c80-4ac3-11ea-9226-88b9ab436d87.jpg)

Also, I've reproduced this with a test: https://github.com/jaredbeck/graph_matching/commit/33c26ac88aba9e7bfdaae68d77a1e0ac7577fe05#diff-01bc23d0a3e2055d77581c14d0d8d2f6R111

I'll play around with this a bit, but no promises. 😅 Coming back to this library after years is a real learning curve! Any suggestions are welcome.

**Comment by jaredbeck** [comment]
Bartosz, If you can please confirm that 79ccac7d9faf4e fixes the issue, then I'll release a new version of the gem.

**Comment by bblimke** [comment]
Thank you for the lightning-fast response @jaredbeck !

I'm sure it takes time to get head around the code after not working on it for years, though after my research I believe it's still number one solution if someone is looking for graph matching in Ruby.

I confirm that https://github.com/jaredbeck/graph_matching/commit/79ccac7d9faf4ef04c9b0f27f1c5af9bfd67d25f fixes the problem.

**Comment by bblimke** [comment]
btw. I appreciate the very descriptive commit message.

**Comment by jaredbeck** [comment]
> I confirm that 79ccac7 fixes the problem.

Great, I'll make a release.

Do you have some more test data for sparse, preferably cyclic bigraphs? We could definitely use more tests.

**Comment by bblimke** [comment]
@jaredbeck thank you for cutting the new release. I'll run it against some more bigraphs today and check if everything works.
